# Summary and Conclusion {#Conclusion}

`r gene_info[[1]]$summary`

`r GeneofInterest` has a well described gene structure with 36 exons, 8 splice variants and only 3 of them are protein coding isoforms. `r GeneofInterest`-201, 202 and 206 are the isoforms (Table 1)labeled as the canonical transcript with CCDS. There are 26 paralogues detected for `r GeneofInterest` (Table 3), and orthologues also detected in Monkey, Mouse, Dog, Rat, Pig and Rabbit for this gene (Table 2).The protein identified for `r GeneofInterest` from UniProtKB is `r uniprotID` with 4 isoforms: O75094-1, O75094-2, O75094-3 and O75094-4.

By analysis of the human BodyMap data, we found high level expression of  `r GeneofInterest` in many tissues including Adipose tissue, Artery, Lung, Bladder, Crebral meanings and thymus, etc.(Figure 2). Comparing with its paralogues, `r GeneofInterest` shows very similar expression pattern with SLIT2 in most tissues (Figure 3). Cross-species analysis indicates that human, dog and rat have very similar expression pattern in most tissues such as Aorta Artery, Adnrenal Gland, Adipose Tissue, etc (Figure 4). High expression of `r GeneofInterest` is found in synovial cell, mesothelial cell, tenocyte, adipocyte and preadipocyte, etc.from FANTOM5 data (Figure 11), and very low expression in most immune cells (Figure 12-13).  HPA data show similar result as Human BodyMap with high expression in Adipose tissues, Bladder, Gallbladder and Lung (Figure 14). Single-cell RNA-seq data indicated high `r GeneofInterest` expression in fibroblasts of skin (> 200 TPM), sertoli cells of testis (> 100 TPM),which matches the HPA expression and BodyMap expression (Figure 15).

Analysis by TCGA data indicated that low to high level `r GeneofInterest` expression is detected in most cancer types except DLBL, AML and Uveal Melanoma (Figure 16), but is up-regulated in Pheochromocytoma & Paraganglioma and down-regulated in Breast invasive carcinoma comparing with expression of adjacent normal tissue (Figure 17). Several cancer cell lines from Neuroblast, Fibroblast show very high expression of `r GeneofInterest` as indicated in Figure 18. 
